src/GTool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('app.urls')),
    path('', include('users.urls')),

    # path('__debug__', include('debug_toolbar.urls')),
]

src/api/urls.py
from django.urls import path
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *

router = routers.SimpleRouter()
router.register(r'image', ImageViewSet)
router.register(r'character', CharacterViewSet)
router.register(r'weapon', WeaponViewSet)

app_name = 'api'
urlpatterns = [
    path('profile/<str:pk>/', ProfileView.as_view(), name='profile-detail'),
    path('constant/', ConstantView.as_view(), name='constant'),
    path('master/', MasterView.as_view(), name='master'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns += router.urls

src/app/urls.py
from django.urls import path
from .views import *

app_name = 'app'
urlpatterns = [
    path('', home, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('inventory/', inventory, name='inventory'),
    path('planner/', planner, name='planner'),
    path('planner/<str:kind>/<str:name>/', planner_detail, name='planner-detail'),
    path('characters/', characters, name='characters'),
    path('characters/<str:name>/', character_detail, name='character-detail'), #MODEL
    path('weapons/', weapons, name='weapons'),
    path('weapons/<str:name>/', weapon_detail, name='weapons-detail'), #MODEL
    path('wishing/', wishing, name='wishing'),
    path('compare/', compare, name='compare'),
    path('data/', data, name='data'),
    
    # CRUDs
    path('adm/', admin, name='admin'),
    
    path('adm/character/', CharacterListView.as_view(), name='character-list'),
    path('adm/character/new/', CharacterCreateView.as_view(), name='character-create'),
    path('adm/character/<int:pk>/', CharacterUpdateView.as_view(), name='character-update'),
    
    path('adm/weapon/', WeaponListView.as_view(), name='weapon-list'),
    path('adm/weapon/new/', WeaponCreateView.as_view(), name='weapon-create'),
    path('adm/weapon/<int:pk>/', WeaponUpdateView.as_view(), name='weapon-update'),
    
    path('adm/boss/', BossListView.as_view(), name='boss-list'),
    path('adm/boss/new/', BossCreateView.as_view(), name='boss-create'),
    path('adm/boss/<int:pk>/', BossUpdateView.as_view(), name='boss-update'),
    
    path('adm/enemy/', EnemyListView.as_view(), name='enemy-list'),
    path('adm/enemy/new/', EnemyCreateView.as_view(), name='enemy-create'),
    path('adm/enemy/<int:pk>/', EnemyUpdateView.as_view(), name='enemy-update'),
    
    path('adm/localspecialty/', LocalSpecialtyListView.as_view(), name='localspecialty-list'),
    path('adm/localspecialty/new/', LocalSpecialtyCreateView.as_view(), name='localspecialty-create'),
    path('adm/localspecialty/<int:pk>/', LocalSpecialtyUpdateView.as_view(), name='localspecialty-update'),
    
    path('adm/weeklyboss/', WeeklyBossListView.as_view(), name='weeklyboss-list'),
    path('adm/weeklyboss/new/', WeeklyBossCreateView.as_view(), name='weeklyboss-create'),
    path('adm/weeklyboss/<int:pk>/', WeeklyBossUpdateView.as_view(), name='weeklyboss-update'),
    
    path('adm/weeklydrop/', WeeklyDropListView.as_view(), name='weeklydrop-list'),
    path('adm/weeklydrop/new/', WeeklyDropCreateView.as_view(), name='weeklydrop-create'),
    path('adm/weeklydrop/<int:pk>/', WeeklyDropUpdateView.as_view(), name='weeklydrop-update'),
    
    path('adm/region/', RegionListView.as_view(), name='region-list'),
    path('adm/region/new/', RegionCreateView.as_view(), name='region-create'),
    path('adm/region/<int:pk>/', RegionUpdateView.as_view(), name='region-update'),
    
    path('adm/book/', BookListView.as_view(), name='book-list'),
    path('adm/book/new/', BookCreateView.as_view(), name='book-create'),
    path('adm/book/<int:pk>/', BookUpdateView.as_view(), name='book-update'),
    
    path('adm/trophy/', TrophyListView.as_view(), name='trophy-list'),
    path('adm/trophy/new/', TrophyCreateView.as_view(), name='trophy-create'),
    path('adm/trophy/<int:pk>/', TrophyUpdateView.as_view(), name='trophy-update'),
]

src/app/templates/adm/_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<form class="form" method="POST">{% csrf_token %}
	<legend class="form__legend">{{ verbose_name|title }}</legend>
	<div class="form__content">
		<div class="content__fields">
			{{ form|crispy }}
		</div>
		<div id="form-images" class="content__images" data-model="{{ verbose_name }}" data-pk="{{ form.instance.pk }}">
			{% for i in img_fields %}
			<img id={{ 'img-'|add:i }} class="js-img content__img">
			{% endfor %}
		</div>
	</div>
	<div class="form__submit">
		{% with 'app:'|add:model_name|add:'-list' as link %}
		<a class="btn btn--clear form__btn" href="{% url link %}">Cancel</a>
		{% endwith %}
		<button class="btn" type="submit">Save</button>
	</div>
</form>

{% endblock content %}

src/app/templates/adm/_list.html
{% extends "app/base.html" %}
{% block content %}

<div id="list" class="list" data-opt={% block opt %}{% endblock %}>
	<a class="btn" href="{% block create %}{% endblock %}">Add New</a>
	<div class="list__container">
		{% for object in object_list %}
		<a class="list__item" href="{% block update %}{% endblock %}">
			{% block list_fields %}{% endblock %}
		</a>
		{% endfor %}
	</div>
</div>

{% endblock content %}

src/app/templates/adm/admin.html
{% extends "app/base.html" %}

{% block content %}

<div class="admin">
	<div class="admin__header">Administration</div>
	<div class="admin__container">
		<div class="admin__group">
			<div class="group__legend">App</div>
			<a class="btn btn--clear admin__link" href="{% url 'app:character-list' %}">Characters</a>
			<a class="btn btn--clear admin__link" href="{% url 'app:weapon-list' %}">Weapons</a>
		</div>
		<div class="admin__group">
			<div class="group__legend">Inventory</div>
			<a class="btn btn--clear admin__link" href="{% url 'app:boss-list' %}">Boss</a>
			<a class="btn btn--clear admin__link" href="{% url 'app:enemy-list' %}">Enemy</a>
			<a class="btn btn--clear admin__link" href="{% url 'app:localspecialty-list' %}">Local Specialty</a>
			<a class="btn btn--clear admin__link" href="{% url 'app:weeklyboss-list' %}">Weekly Boss</a>
			<a class="btn btn--clear admin__link" href="{% url 'app:weeklydrop-list' %}">Weekly Drop</a>
		</div>
		<div class="admin__group">
			<div class="group__legend">Regional</div>
			<a class="btn btn--clear admin__link" href="{% url 'app:region-list' %}">Region</a>
			<a class="btn btn--clear admin__link" href="{% url 'app:book-list' %}">Book</a>
			<a class="btn btn--clear admin__link" href="{% url 'app:trophy-list' %}">Trophy</a>
		</div>
	</div>
</div>

{% endblock content %}

{% block extrastyle %}
<style>
.admin{
	--header-txclr: var(--clr-comet-dkr);
	--header-bgclr: var(--clr-ecru);
	
	--legend-txclr: var(--clr-comet-dkr);
	--legend-bgclr: var(--clr-ecru-dk);
	
	--group-txclr: var(--clr-comet);
	--group-bgclr: var(--clr-ecru-lt);
}

.admin__header{
	font-size: 3em;
	padding: 0.75em;
	text-align: center;
	background-color: var(--header-bgclr);
	color: var(--header-txclr);
	font-weight: bolder;
}

.admin__container{
	display: grid;
	gap: 1em;
	padding: 2em;
}

.admin__group{
	background-color: var(--group-bgclr);
}

.group__legend{
	font-size: 2em;
	padding: 0.4em;
	background-color: var(--legend-bgclr);
	color: var(--legend-txclr);
	font-weight: bolder;
}

.admin__link{
	--btn-txclr: var(--group-txclr);

	border-radius: 0;
	border-bottom: 0.1em solid var(--group-txclr);
	place-content: center start;
}
</style>
{% endblock extrastyle %}

src/app/templates/adm/book_list.html
{% extends "adm/_list.html" %}

{% block opt %}"b"{% endblock%}
{% block create %}{% url 'app:book-create' %}{% endblock%}
{% block update %}{% url 'app:book-update' object.id %}{% endblock%}
{% block list_fields %}

<div>{{ object.id }}</div>
<div>{{ object.region }}</div>
<div>{{ object.name }}</div>
<img class="js-img list__image" data-r="2" data-src="{{ object.name }}">
<img class="js-img list__image" data-r="3" data-src="{{ object.name }}">
<img class="js-img list__image" data-r="4" data-src="{{ object.name }}">

{% endblock%}

src/app/templates/adm/boss_list.html
{% extends "adm/_list.html" %}

{% block opt %}"BOSSES"{% endblock%}
{% block create %}{% url 'app:boss-create' %}{% endblock%}
{% block update %}{% url 'app:boss-update' object.id %}{% endblock%}
{% block list_fields %}

<div>{{ object.id }}</div>
<img class="js-img list__image" data-src="{{ object.code }}">
<div>{{ object.name }}</div>
<div>{{ object.code }}</div>

{% endblock%}

src/app/templates/adm/character_list.html
{% extends "adm/_list.html" %}

{% block opt %}"c"{% endblock%}
{% block create %}{% url 'app:character-create' %}{% endblock%}
{% block update %}{% url 'app:character-update' object.id %}{% endblock%}
{% block list_fields %}

<div>{{ object.id }}</div>
<img class="js-img list__image" data-src="{{ object.name }}">
<div>{{ object.name }}</div>
<div>{{ object.version }}</div>
<div>{{ object.region }}</div>
<div>{{ object.rarity }}</div>

{% endblock%}

src/app/templates/adm/enemy_list.html
{% extends "adm/_list.html" %}

{% block opt %}"ENEMIES"{% endblock%}
{% block create %}{% url 'app:enemy-create' %}{% endblock%}
{% block update %}{% url 'app:enemy-update' object.id %}{% endblock%}
{% block list_fields %}

<div>{{ object.id }}</div>
<input type="checkbox" style="pointer-events: none;" {% if object.is_elite == True %}checked={% endif %}>
<div>{{ object.name }}</div>
<img class="js-img list__image" data-src="{{ object.low }}">
<img class="js-img list__image" data-src="{{ object.mid }}">
<img class="js-img list__image" data-src="{{ object.high }}">

{% endblock%}

src/app/templates/adm/localspecialty_list.html
{% extends "adm/_list.html" %}

{% block opt %}"LOCAL_SPECIALTIES"{% endblock%}
{% block create %}{% url 'app:localspecialty-create' %}{% endblock%}
{% block update %}{% url 'app:localspecialty-update' object.id %}{% endblock%}
{% block list_fields %}

<div>{{ object.id }}</div>
<img class="js-img list__image" data-src="{{ object.name }}">
<div>{{ object.name }}</div>
<div>{{ object.region }}</div>
<div>{{ object.inv_order }}</div>

{% endblock%}

src/app/templates/adm/region_list.html
{% extends "adm/_list.html" %}

{% block opt %}"REGIONS"{% endblock%}
{% block create %}{% url 'app:region-create' %}{% endblock%}
{% block update %}{% url 'app:region-update' object.id %}{% endblock%}
{% block list_fields %}

<div>{{ object.id }}</div>
<img class="js-img list__image" data-src="{{ object.code }}">
<div>{{ object.name }}</div>
<div>{{ object.code }}</div>

{% endblock%}

src/app/templates/adm/trophy_list.html
{% extends "adm/_list.html" %}

{% block opt %}"t"{% endblock%}
{% block create %}{% url 'app:trophy-create' %}{% endblock%}
{% block update %}{% url 'app:trophy-update' object.id %}{% endblock%}
{% block list_fields %}

{% comment %} <div>{{ object.id }}</div> {% endcomment %}
{% comment %} <div>{{ object.region }}</div> {% endcomment %}
<input type="checkbox" style="pointer-events: none;" {% if object.insert_code == True %}checked={% endif %}>
<img class="js-img list__image" data-src="{{ object.n2 }}" data-code="{{ object.code }}" data-ic="{{ object.insert_code }}">
<img class="js-img list__image" data-src="{{ object.n3 }}" data-code="{{ object.code }}" data-ic="{{ object.insert_code }}">
<img class="js-img list__image" data-src="{{ object.n4 }}" data-code="{{ object.code }}" data-ic="{{ object.insert_code }}">
<img class="js-img list__image" data-src="{{ object.n5 }}" data-code="{{ object.code }}" data-ic="{{ object.insert_code }}">
<div>{{ object.code }}</div>
<div>{{ object.name }}</div>

{% endblock%}

src/app/templates/adm/weapon_list.html
{% extends "adm/_list.html" %}

{% block opt %}"w"{% endblock%}
{% block create %}{% url 'app:weapon-create' %}{% endblock%}
{% block update %}{% url 'app:weapon-update' object.id %}{% endblock%}
{% block list_fields %}

<div>{{ object.id }}</div>
<img class="js-img list__image" data-src="{{ object.name }}">
<div>{{ object.name }}</div>
<div>{{ object.version }}</div>
<input type="checkbox" style="pointer-events: none;" {% if object.is_wish_only == True %}checked={% endif %}>
<div>{{ object.rarity }}</div>
<div>{{ object.weapon_type }}</div>

{% endblock%}

src/app/templates/adm/weeklyboss_list.html
{% extends "adm/_list.html" %}

{% block opt %}"WEEKLY_BOSSES"{% endblock%}
{% block create %}{% url 'app:weeklyboss-create' %}{% endblock%}
{% block update %}{% url 'app:weeklyboss-update' object.id %}{% endblock%}
{% block list_fields %}

<div>{{ object.id }}</div>
<img class="js-img list__image" data-src="{{ object.code }}">
<div>{{ object.name }}</div>
<div>{{ object.code }}</div>

{% endblock%}

src/app/templates/adm/weeklydrop_list.html
{% extends "adm/_list.html" %}

{% block opt %}"WEEKLY_DROPS"{% endblock%}
{% block create %}{% url 'app:weeklydrop-create' %}{% endblock%}
{% block update %}{% url 'app:weeklydrop-update' object.id %}{% endblock%}
{% block list_fields %}

<div>{{ object.id }}</div>
<img class="js-img list__image" data-src="{{ object.code }}">
<div>{{ object.name }}</div>
<div>{{ object.weekly_boss }}</div>
<div>{{ object.code }}</div>

{% endblock%}