src/GTool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('app.urls')),
    path('', include('users.urls')),

    # path('__debug__', include('debug_toolbar.urls')),
]

src/api/urls.py
from django.urls import path
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *

router = routers.SimpleRouter()
router.register(r'image', ImageViewSet)
router.register(r'character', CharacterViewSet)
router.register(r'weapon', WeaponViewSet)

app_name = 'api'
urlpatterns = [
    path('profile/<str:pk>/', ProfileView.as_view(), name='profile-detail'),
    path('constant/', ConstantView.as_view(), name='constant'),
    path('master/', MasterView.as_view(), name='master'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns += router.urls

src/app/urls.py
from django.urls import path
from .views import *

app_name = 'app'
urlpatterns = [
    path('', home, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('inventory/', inventory, name='inventory'),
    path('planner/', planner, name='planner'),
    path('planner/<str:kind>/<str:name>/', planner_detail, name='planner-detail'),
    path('characters/', characters, name='characters'),
    path('characters/<str:name>/', character_detail, name='character-detail'), #MODEL
    path('weapons/', weapons, name='weapons'),
    path('weapons/<str:name>/', weapon_detail, name='weapons-detail'), #MODEL
    path('wishing/', wishing, name='wishing'),
    path('compare/', compare, name='compare'),
    path('data/', data, name='data'),
    
    # CRUDs
    path('adm/', admin, name='admin'),
    
    path('adm/character/', CharacterListView.as_view(), name='character-list'),
    path('adm/character/new/', CharacterCreateView.as_view(), name='character-create'),
    path('adm/character/<int:pk>/', CharacterUpdateView.as_view(), name='character-update'),
    
    path('adm/weapon/', WeaponListView.as_view(), name='weapon-list'),
    path('adm/weapon/new/', WeaponCreateView.as_view(), name='weapon-create'),
    path('adm/weapon/<int:pk>/', WeaponUpdateView.as_view(), name='weapon-update'),
    
    path('adm/boss/', BossListView.as_view(), name='boss-list'),
    path('adm/boss/new/', BossCreateView.as_view(), name='boss-create'),
    path('adm/boss/<int:pk>/', BossUpdateView.as_view(), name='boss-update'),
    
    path('adm/enemy/', EnemyListView.as_view(), name='enemy-list'),
    path('adm/enemy/new/', EnemyCreateView.as_view(), name='enemy-create'),
    path('adm/enemy/<int:pk>/', EnemyUpdateView.as_view(), name='enemy-update'),
    
    path('adm/localspecialty/', LocalSpecialtyListView.as_view(), name='localspecialty-list'),
    path('adm/localspecialty/new/', LocalSpecialtyCreateView.as_view(), name='localspecialty-create'),
    path('adm/localspecialty/<int:pk>/', LocalSpecialtyUpdateView.as_view(), name='localspecialty-update'),
    
    path('adm/weeklyboss/', WeeklyBossListView.as_view(), name='weeklyboss-list'),
    path('adm/weeklyboss/new/', WeeklyBossCreateView.as_view(), name='weeklyboss-create'),
    path('adm/weeklyboss/<int:pk>/', WeeklyBossUpdateView.as_view(), name='weeklyboss-update'),
    
    path('adm/weeklydrop/', WeeklyDropListView.as_view(), name='weeklydrop-list'),
    path('adm/weeklydrop/new/', WeeklyDropCreateView.as_view(), name='weeklydrop-create'),
    path('adm/weeklydrop/<int:pk>/', WeeklyDropUpdateView.as_view(), name='weeklydrop-update'),
    
    path('adm/region/', RegionListView.as_view(), name='region-list'),
    path('adm/region/new/', RegionCreateView.as_view(), name='region-create'),
    path('adm/region/<int:pk>/', RegionUpdateView.as_view(), name='region-update'),
    
    path('adm/book/', BookListView.as_view(), name='book-list'),
    path('adm/book/new/', BookCreateView.as_view(), name='book-create'),
    path('adm/book/<int:pk>/', BookUpdateView.as_view(), name='book-update'),
    
    path('adm/trophy/', TrophyListView.as_view(), name='trophy-list'),
    path('adm/trophy/new/', TrophyCreateView.as_view(), name='trophy-create'),
    path('adm/trophy/<int:pk>/', TrophyUpdateView.as_view(), name='trophy-update'),
]

src/app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
	<base target="_self">
	{% if title %}
		<title>GTool - {{ title }}</title>
	{% else %}
		<title>GTool</title>
	{% endif %}

	<link rel="shortcut icon" type="image/png" href="{% static 'app/assets/favicon.ico' %}"/>

	<link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">
	{% if styles %}{% for style in styles %}
		<link rel="stylesheet" type="text/css" href="{% static style %}">
	{% endfor %}{% endif %}
	{% block extrastyle %}{% endblock %}

	{% if user.is_authenticated %}{{ user.profile.data|json_script:"json_user_data" }}{% endif %}
	{% if user.is_authenticated %}{{ user.profile.id|json_script:"json_user_id" }}{% endif %}

	<script src="{% static 'app/database.js' %}"></script>
	<script src="{% static 'app/main.js' %}"></script>
	{% if scripts %}{% for script in scripts %}
		<script src="{% static script %}"></script>
	{% endfor %}{% endif %}
	{% block extrascript %}{% endblock %}

</head>
<body>
	{% include 'app/menu.html' %}
	<dialog id='resin-dialog' class="resin" onclick="if(event.target === this) this.close()">
		<div class="resin__header">
			<button class="btn resin__btn icon-box" onclick="document.getElementById('resin-dialog').close()">
				<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#X" /></svg>
			</button>
		</div>
		<div class="resin__body">
			<div id="resin-results" class="resin__display"></div>
			<input id="resin-input" class="resin__input" type="text" pattern="\d*" oninput="makeResinDialog()">
		</div>
	</dialog>

	<dialog id="pop-up"></dialog>
	
	<dialog id="alert" class="alert" onclick="this.close(); this.innerHTML = ''"></dialog>

	<main>
		{% block content %}{% endblock %}
	</main>

</body>
</html>

src/app/templates/app/character_detail.html
{% extends "app/base.html" %}
{% load static %}

{% block content %}

<div class="dets char" data-color={{ object.element }}>
  <a class="btn btn--clear icon-box dets__close" href="{% url 'app:characters' %}">
		<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#X"/></svg>
	</a>
	
  <div class="dets__content">
		
		<div class="dets__banner">
			<div class="banner__overlay"></div>
			<img class="banner__img" data-img='CHARACTER,{{ object.name }}'>
		</div>

    <div class="dets__info">
      <div>
        <div id="name" class="info__name">{{ object.name }}</div>
        <img class="info__element" data-img='ELEMENTS,{{ object.element }}'>
        <div class="info__editing">
					<div id="constellations" class="info__enhancements">
						<div id="constellation"></div>
						<div id="details" class="enhancement__details"></div>
					</div>
          <div id="modify" class="info__modify hide">
            <button onclick="minus(true)">[-]</button>
            <button onclick="plus(true)">[+]</button>
            <button onclick="minus()">-</button>
            <button onclick="plus()">+</button>
          </div>
        </div>
        <button id="edit" class="info__edit" onclick="editIn()">
          <svg id="pencil" viewBox="0 0 24 24"><path d="M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z"></path></svg>
          <svg id="disk" class="hide" viewBox="0 0 24 24"><path d="M15,9H5V5H15M12,19A3,3 0 0,1 9,16A3,3 0 0,1 12,13A3,3 0 0,1 15,16A3,3 0 0,1 12,19M17,3H5C3.89,3 3,3.9 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V7L17,3Z"></path></svg>
        </button>
      </div>
      <div>
        <div data-stars={{ object.rarity }}></div>
        <div>{{ object.weapon_type }}</div>
      </div>
    </div>

		<div class="dets__data">

			<div class="data__inputs">
				<div class="input__farm">
					<input type="checkbox" id="FARM" onchange="update(this)">
					Farm
				</div>
				<div class="input__group phase">
					<div class="input__group__text">Phase</div>
					<input type="text" pattern="\d*" id="PHASE" onchange="update(this)" onclick="focusInput(event)">
					<input type="text" pattern="\d*" id="TARGET" onchange="update(this)" onclick="focusInput(event)">
				</div>
				<div class="input__group normal">
					<div class="input__group__text">Normal</div>
					<input type="text" pattern="\d*" id="NORMAL" onchange="update(this)" onclick="focusInput(event)">
					<input type="text" pattern="\d*" id="TNORMAL" onchange="update(this)" onclick="focusInput(event)">
				</div>
				<div class="input__group skill">
					<div class="input__group__text">Skill</div>
					<input type="text" pattern="\d*" id="SKILL" onchange="update(this)" onclick="focusInput(event)">
					<input type="text" pattern="\d*" id="TSKILL" onchange="update(this)" onclick="focusInput(event)">
				</div>
				<div class="input__group burst">
					<div class="input__group__text">Burst</div>
					<input type="text" pattern="\d*" id="BURST" onchange="update(this)" onclick="focusInput(event)">
					<input type="text" pattern="\d*" id="TBURST" onchange="update(this)" onclick="focusInput(event)">
				</div>
			</div>
			
			<div class="data__mats">
				<div class="mat__title">Ascension Materials</div>
				<div class="mat__img"><img data-img='BOSSES,{{ object.boss|default:"" }}'></div>
				<div class="mat__img"><img data-img='LOCAL_SPECIALTIES,{{ object.local_specialty }}'></div>
				<div class="mat__img"><img data-img='ENEMIES,{{ object.common }}'></div>
			</div>
	
			<div class="data__mats">
				<div class="mat__title">Talent Materials</div>
				<div class="mat__img"><img data-img='BOOKS,{{ object.book|default:"" }}'></div>
				<div class="mat__img"><img data-img='WEEKLY_BOSSES,{{ object.weekly_boss|default:"" }}'></div>
				<div class="mat__img"><img data-img='WEEKLY_DROPS,{{ object.weekly_drop|default:"" }}'></div>
			</div>
			
			<div class="data__stats">
				<div>HP</div>
				<div>{{ object.stat_hp }}</div>
				<div>ATK</div>
				<div>{{ object.stat_atk }}</div>
				<div>DEF</div>
				<div>{{ object.stat_def }}</div>
				<div>{{ object.stat }}</div>
				<div>{{ object.stat_value }}</div>
			</div>

		</div>

	</div>
</div>

{% endblock content %}

src/app/templates/app/characters.html
{% extends "app/base.html" %}
{% load static %}

{% block content %}

<div class="options">
	<select id="select-sort" class="options__select" onchange="setSort(value)">
		<option disabled selected hidden>Sort by ...</option>
		<option value="0">Release Date</option>
		<option value="1">Name</option>
		<option value="2">Ascension</option>
		<option value="3">Rarity</option>
		<option value="4">Constellations</option>
	</select>
	<button id="direction" class="btn icon-box options__direction" onclick="toggleDirection(this)"></button>
	<div class="mode">
		<button class="js-mode btn icon-box mode__btn selected" onclick="switcher(this, false)">
			<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#view_module" /></svg>
		</button>
		<button class="js-mode btn icon-box mode__btn" onclick="switcher(this, true)" >
			<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#view_list" /></svg>
		</button>
	</div>
</div>

<div class="characters">
	<div id="char-grid" class="grid">
	</div>
	
	<table id="char-table" class="hide">
		<thead>
			<th onclick="setSort(1, this)"></th>
			<th id="hdr-name" class="row__r-border" onclick="setSort(2, this)">Name</th>
			<th onclick="setSort(3, this)">P</th>
			<th onclick="setSort(4, this)">N</th>
			<th onclick="setSort(5, this)">S</th>
			<th class="row__r-border" onclick="setSort(6, this)">B</th>
			<th onclick="setSort(7, this)">HP</th>
			<th onclick="setSort(8, this)">ATK</th>
			<th onclick="setSort(9, this)">DEF</th>
			<th onclick="setSort(10, this)">STAT</th>
		</thead>
		<tbody id="table__body"></tbody>
	</table>
</div>

{% endblock content %}

src/app/templates/app/compare.html
{% extends "app/base.html" %}

{% block content %}

<div id="compare" class="compare">
	<div class="cmp__stub">
		<select id="row" class="select select--row" onchange="renderCompare()">
			<option disabled selected hidden>...</option>
			<option>Element</option>
			<option>Weapon Type</option>
			<option>Model</option>
			<option>Region</option>
			<option>Boss</option>
			<option>Local Specialty</option>
			<option>Common</option>
			<option>Book</option>
			<option>Weekly Boss</option>
			<option>Weekly Drop</option>
			<option>Stat</option>
		</select>
		<select id="col" class="select select--col" onchange="renderCompare()">
			<option>...</option>
			<option>Rarity</option>
			<option>Element</option>
			<option>Weapon Type</option>
			<option>Model</option>
			<option>Region</option>
			<option>Boss</option>
			<option>Local Specialty</option>
			<option>Common</option>
			<option>Book</option>
			<option>Weekly Boss</option>
			<option>Weekly Drop</option>
			<option>Stat</option>
		</select>
	</div>
	<div id="cols" class="area"></div>
	<div id="rows" class="area"></div>
	<div id="table" class="area"></div>
</div>

{% endblock content %}

src/app/templates/app/dashboard.html
{% extends "app/base.html" %}

{% block content %}

<div id='home' class="home">
	<div class="group group-domain">
		<section id="BOOKS" class="section section--total hide"></section>
		<section id="TROPHIES" class="section section--total hide"></section>
	</div>
	<div class="group group-gems">
		<section id="GEMS" class="section section--total hide"></section>
	</div>
	<div class="group group-enemies">
		<section id="ELITE" class="section section--total hide"></section>
		<section id="COMMON" class="section section--total hide"></section>
	</div>
	<div class="group group-singles">
		<section id="RESOURCES" class="section hide"></section>
		<section id="WEEKLY_DROPS" class="section hide"></section>
		<section id="BOSSES" class="section hide"></section>
		<div class="break"></div>
		<section id="LOCAL_SPECIALTIES" class="section hide"></section>
	</div>
</div>

{% endblock content %}

src/app/templates/app/data.html
{% extends "app/base.html" %}

{% block content %}

<div id="content" class="content"></div>

{% endblock content %}

src/app/templates/app/home.html
{% extends "app/base.html" %}
{% load static %}

{% block content %}

<div class="home">
	<div class="home__container">
		<div class="home__header">Welcome {{ user.username }}!</div>
	</div>
	<div class="home__container">
		{% for page, link in nav.items %}{% url link as url %}
		{% if page != 'HOME'%}
			<a class="btn home__link" href="{{ url }}">
				<div class="icon-box">
					<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#{{ page }}" /></svg>
				</div>
				<p class="link__text">{{ page|upper }}</p>
			</a>
		{% endif %}
		{% endfor %}
		{% if not user.is_authenticated %}<a class="btn home__link" href="{% url 'login' %}">Login</a>{% endif %}
		{% if user.is_staff %}<a class="btn home__link" href="{% url 'app:admin' %}">Admin</a>{% endif %}
	</div>
</div>

{% endblock content %}

{% block extrastyle %}
<style>
.home{
	--container-txclr: var(--clr-comet-dkr);
	--container-bgclr: var(--clr-ecru);

	padding: 1em;
}

.home__container{
	display: flex;
	flex-wrap: wrap;
	place-content: center;
	margin-top: 1em;
	padding: 0.75em;
	gap: 0.75em;
	border-radius: 0.5em;
	background-color: var(--container-bgclr);
	color: var(--container-txclr);
}

.home__header{
	font-size: 3em;
	word-break: break-word;
	font-weight: bolder;
	text-align: center;
}

.home__link{
	grid-auto-flow: row;
	place-content: center;
	min-width: 7em;
	gap: 0.5em;
	aspect-ratio: 1;
	font-weight: bold;
}

.link__text{
	font-size: 0.75em;
}
</style>
{% endblock extrastyle %}

src/app/templates/app/inventory.html
{% extends "app/base.html" %}

{% block content %}

<div class="inv">
	<section id="RESOURCES" class="section"></section>
	<section id="ENEMIES" class="section"></section>
	<section id="WEEKLY_DROPS" class="section"></section>
	<section id="BOSSES" class="section"></section>
	<section id="GEMS" class="section"></section>
	<section id="BOOKS" class="section"></section>
	<section id="TROPHIES" class="section"></section>
	<section id="LOCAL_SPECIALTIES" class="section"></section>
</div>

{% endblock content %}

src/app/templates/app/menu.html
{% load static %}
<nav id="nav" class="nav">
	<div id="backdrop" onclick="closeNav()"></div>
	<aside class="nav__container">
		<section class="nav__content">
			<div class="nav__top">
				<button class="btn nav__btn icon-box" onclick="reset(); window.location.reload()">
					<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#Reload" /></svg>
				</button>
				{% if user.is_authenticated %}
					<a class="nav__profile" href="#">
						<div class="btn btn--ii icon-box">
							<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#Profile" /></svg>
						</div>
						<p class="nav__username" >{{user.username}}</p>
					</a>
				{% endif %}
			</div>
			<div class="nav__links">
				{% for page, link in nav.items %}{% url link as url %}
					<a
						{% if page == 'HOME' and request.path == "/" or url != "/" and url in request.path|urlencode %}
							href="javascript:void(0)" class=" nav__link nav__link--active"
						{% else %}
							href="{{ url }}" class="nav__link" 
						{% endif %}
					>
						<div class="icon-box">
							<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#{{ page }}" /></svg>
						</div>
						<p>{{ page|upper }}</p>
					</a>
				{% endfor %}
			</div>
			<div class="nav__bottom">
				{% if user.is_authenticated %}
					<form method="post" action="{% url 'logout' %}">{% csrf_token %}
						<button class="btn btn--clear icon-box" onclick="console.log('logout')" type="submit">
								<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#Logout" /></svg>
						</button>
					</form>
				{% endif %}
				{% if user.is_staff %}
					<a class="btn" href="{% url 'app:admin' %}">Admin</a>
				{% endif %}
			</div>
		</section>
	</aside>
</nav>

<header class="header">
	<button class="btn btn--clear icon-box" onclick="document.getElementById('resin-dialog').showModal()">
		<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#Resin" /></svg>
	</button>
	<div class="switch hidden">
		<input type="checkbox" class="switch__input" onchange="toggleSwitch(this)" id="switch">
		<label class="switch__cont" for="switch">
			<div class="switch__slider icon-box">
				<svg class="icon switch__icon--unchecked"><use href="{%static 'app/assets/sprites.svg'%}#X" /></svg>
				<svg class="icon switch__icon--checked"><use href="{%static 'app/assets/sprites.svg'%}#Check" /></svg>
			</div>
		</label>
	</div>
	{% if user.is_authenticated %}
		<button class="btn header__btn" onclick="saveUser()">
			<div class="header__icon icon-box">
				<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#Save" /></svg>
			</div>
			<div class="header__btn-txt">Save</div>
		</button>
	{% endif %}
</header>

<footer class="footer">
	<button class="footer__menu icon-box" onclick="openNav()">
		<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#Menu" /></svg>
	</button>
	{% for page, link in nav.items %}
	{% if page|upper in "DASHBOARD INVENTORY PLANNER CHARACTERS WEAPONS" %}
		{% url link as url %}
		<a
			{% if page == 'HOME' and request.path == "/" or url != "/" and url in request.path|urlencode %}
				href="javascript:void(0)" class="footer__link footer__link--active"
			{% else %}
				href="{{ url }}" class="footer__link" 
			{% endif %}
		>
			<div class="icon-box">
				<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#{{ page }}" /></svg>
			</div>
		</a>
	{% endif %}{% endfor %}
</footer>

src/app/templates/app/planner.html
{% extends "app/base.html" %}

{% block content %}

{% url 'app:planner-detail' 'character' '*' as c_url %}
{% url 'app:planner-detail' 'weapon' '*' as w_url %}

<div class="planner">
	<section id="Characters" class="planner__section" data-url="{{c_url}}"></section>
	<section id="Weapons" class="planner__section" data-url="{{w_url}}"></section>
</div>

{% endblock content %}

src/app/templates/app/planner_detail.html
{% extends "app/base.html" %}
{% load static %}

{% block content %}

<div id="page" class="page" data-kind="{{kind}}" data-name="{{name}}">
	<details>
		<summary class="page__summary">
			<div class="page__header">
				<img id="page-image" class="page__image">
				<div class="page__name">{{name}}</div>
				<a class="btn page__close icon-box" href="{% url 'app:planner' %}">
					<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#X"/></svg>
				</a>
			</div>
		</summary>
		<div id="page-edit" class="page__edit"></div>
	</details>
  <div id="page-inventory" class="page__inventory"></div>
  <div id="upgrade" class="page__upgrade">
		<div id="upgrade-area" class="upgrade__area"></div>
		<div id="upgrade-next" class="upgrade__next hide"></div>
	</div>
</div>

{% endblock content %}

src/app/templates/app/test.html
{% extends "app/base.html" %}

{% block content %}
	<h1>{{category}}</h1>
{% endblock content %}

src/app/templates/app/weapons.html
{% extends "app/base.html" %}

{% block content %}

<div class="options">
	<div class="options__filters">
		<button class="btn icon-box options__wtype" onclick="filterWpn(this, 1)"><img class="js-wtype"></button>
		<button class="btn icon-box options__wtype" onclick="filterWpn(this, 2)"><img class="js-wtype"></button>
		<button class="btn icon-box options__wtype" onclick="filterWpn(this, 3)"><img class="js-wtype"></button>
		<button class="btn icon-box options__wtype" onclick="filterWpn(this, 4)"><img class="js-wtype"></button>
		<button class="btn icon-box options__wtype" onclick="filterWpn(this, 5)"><img class="js-wtype"></button>
	</div>
	<button id="direction" class="btn options__direction" onclick="toggleDirection(this)"></button>
	<div class="options__owned">
		<button class="js-own btn owned__btn" onclick="filterNonOwned(this, true)">Owned</button>
		<button class="js-own btn owned__btn" onclick="filterNonOwned(this, false)">All</button>
	</div>
</div>

<table id="table">
	<thead>
		<th onclick="setSort(this, 1)"></th>
		<th onclick="setSort(this, 2)"></th>
		<th onclick="setSort(this, 3)">Name</th>
		<th onclick="setSort(this, 4)">P</th>
		<th onclick="setSort(this, 5)">ATK</th>
		<th onclick="setSort(this, 6)">STAT</th>
		<th onclick="setSort(this, 7)">TRP</th>
		<th onclick="setSort(this, 8)">ELT</th>
		<th onclick="setSort(this, 9)">CMN</th>
	</thead>
	<tbody id="weapons"></tbody>
</table>

{% endblock content %}

src/app/templates/app/wishing.html
{% extends "app/base.html" %}
{% load static %}

{% block content %}

<div class="wishing-panel">

<div class="wishing">
	<div class="wishing__options">
		<div class="wishing__settings">
			<button class="btn options__btn" onclick="toggleSettings(this)">
				<div class="icon-box">
					<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#Settings" /></svg>
				</div>
			</button>
			<div id="wishing-settings" class="settings__content hide">
				<button class="btn" onclick="showChecks('5C')">Standard Characters</button>
				<button class="btn" onclick="showChecks('5W')">Standard Weapons</button>
				<button class="btn" onclick="showChecks('4W')">Wishable Weapons</button>
			</div>
		</div>
		<button class="btn options__btn" onclick="showChecks('4C')">Set Featured</button>
	</div>
	<div class="wishing__btns">
		<button class="btn wishing__btn" onclick="showWish(true,5)" data-color="5">
			<div class="icon-box">
				<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#CHARACTERS" /></svg>
			</div>
			<span class="wishing__stars" data-stars="5"></span>
		</button>
		<button class="btn wishing__btn" onclick="showWish(false,5)" data-color="5">
			<div class="icon-box">
				<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#WEAPONS" /></svg>
			</div>
			<span class="wishing__stars" data-stars="5"></span>
		</button>
		<button class="btn wishing__btn" onclick="showWish(true,4)" data-color="4">
			<div class="icon-box">
				<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#CHARACTERS" /></svg>
			</div>
			<span class="wishing__stars" data-stars="4"></span>
		</button>
		<button class="btn wishing__btn" onclick="showWish(false,4)" data-color="4">
			<div class="icon-box">
				<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#WEAPONS" /></svg>
			</div>
			<span class="wishing__stars" data-stars="4"></span>
		</button>
	</div>
</div>

<div class="preview" id="preview">
</div>

<div class="confirm hide" id="confirm">
	<button class="btn" onclick="addWishes()">
		<div class="icon-box">
			<svg class="icon"><use href="{%static 'app/assets/sprites.svg'%}#WISHING" /></svg>
		</div>
		<div>Add</div>
	</button>
</div>

</div>

{% endblock content %}